cat99/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :cats do 
    resources :cat_rental_requests, only:[:index]
  end 
  
  resources :cat_rental_requests, only:[:create, :new, :update, :edit]
  
end

cat99/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

cat99/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :bigint(8)        not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text             not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

require 'date'

COLORS = ['Black', 'White', 'Brown']
class Cat < ApplicationRecord
  validates :birth_date, :name, :description, presence: true
   
  validate :birth_date_not_in_future
  
  validates :color, presence: true, inclusion: { 
    in: COLORS, 
    message: "Invalid color" 
  }
  
  validates :sex, presence: true, inclusion: { 
    in: %w(M F), 
    message: "Invalid gender" 
  }
  
  has_many :cat_rental_requests,
    primary_key: :id,
    foreign_key: :cat_id, 
    class_name: :CatRentalRequest,
    dependent: :destroy
  
  def birth_date_not_in_future
    if self.birth_date && self.birth_date > Date.today
      errors.add(:birth_date, "cannot be in the future")
    end 
  end 
  
  def age 
    now = Date.today 
    age = ((now - self.birth_date).to_i / 365.25).to_i
  end 
  
end

cat99/app/models/cat_rental_request.rb
# == Schema Information
#
# Table name: cat_rental_requests
#
#  id         :bigint(8)        not null, primary key
#  cat_id     :integer          not null
#  start_date :date             not null
#  end_date   :date             not null
#  status     :string           default("PENDING")
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class CatRentalRequest < ApplicationRecord
  validates :cat_id, :start_date, :end_date, presence: true  
  
  validates :status, presence: true, inclusion: {
    in: ["APPROVED", "PENDING", "DENIED"], 
    message: "Invalid status" 
  }
  
  validate :valid_start_and_end_date, :does_not_overlap_approved_request
  
  belongs_to :cat,
    primary_key: :id,
    foreign_key: :cat_id, 
    class_name: "Cat" 
  
  def valid_start_and_end_date
    if self.start_date && self.end_date && self.start_date > self.end_date
      errors.add(:start_date, "cannot be after end date")
    end 
  end 
  
  def overlapping_requests 
    if self.start_date && self.end_date
      current_requests = CatRentalRequest
        .where(cat_id: self.cat_id)
        .where.not('end_date < ? OR start_date > ?', self.start_date, self.end_date)
    end 
  end
  
  def does_not_overlap_approved_request 
    if self.start_date && self.end_date && overlapping_approved_requests.exists?
      errors.add(:start_date, "cannot overlap approved request")
    end 
  end 
  
  def overlapping_approved_requests
    if self.start_date && self.end_date
      overlapping_requests.where(status: 'APPROVED')
    end 
  end 
  
  def overlapping_pending_requests
    if self.start_date && self.end_date
      overlapping_requests.where(status: 'PENDING')
    end 
  end 
  
  
end

cat99/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

cat99/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController 
  
  def new 
    @cats = Cat.all 
    render :new
  end 
  
end 

cat99/app/controllers/cats_controller.rb
class CatsController < ApplicationController 
  
  def index 
    @cats = Cat.all 
    render :index
  end 
  
  def show 
    @cat = Cat.find(params[:id])
    render :show
  end 
  
  
  def new
    @cat = Cat.new 
    render :new
  end 
  
  def create
    @cat = Cat.new(cat_params)
    
    if @cat.save
      redirect_to cat_url(@cat)
    else 
      render json: @cat.errors.full_messages, status: 418
    end 
  end 
  
  def edit 
    @cat = Cat.find(params[:id])
    render :edit
  end 
  
  def update 
    cat = Cat.find(params[:id])
  
    if cat.update(cat_params)
      redirect_to cat_url(cat)
    else 
      render json: cat.errors.full_messages, status: 418
    end 
  end 
  
  private 
  
  def cat_params 
    params.require(:cat).permit(:name, :birth_date, :sex, :color, :description)
  end 
  
end 

cat99/app/helpers/application_helper.rb
module ApplicationHelper
end

cat99/app/views/cat_rental_requests/new.html.erb
New Rental Request

<form action="/" method="post">
  
  <label>
    Select Cat: 
    <select name="cat[name]">
      <option value="" disabled selected>Choose Cat</option>
      <% @cats.each do |cat| %>
        <option value="<%= cat.name %>"><%= cat.name %></option>
      <% end %>
    </select>
  </label>
  <br/>
  
  
</form>

cat99/app/views/cats/_cat_form.html.erb
<% if action == :new %>
  <% action_url = cats_url %>
  <% button_value = "Create New Cat!" %>
<% else %>
  <% action_url = cat_url(cat) %>
  <% button_value = "Edit Cat!" %>
<% end %>


<form action="<%= action_url %>" method="post">
  <% if action == :edit %>
    <input type="hidden" name="_method" value="patch"></input>
  <% end %>
  
  <label>
    Name: <input type="text" name="cat[name]" value="<%= cat.name %>"></input>
  </label>
  <br/>
  
  <label>
    Birth Date: <input type="date" name="cat[birth_date]" value="<%= cat.birth_date %>"></input>
  </label>
  <br/>
  
  <label>
    Color: 
    <select name="cat[color]">
      <option value="" disabled <%= action == :new ? "selected" : "" %>>Choose Color</option>
      <option value="Black" <%= action == :edit && cat.color == "Black" ? "selected" : "" %>>Black</option>
      <option value="Brown" <%= action == :edit && cat.color == "Brown" ? "selected" : "" %>>Brown</option>
      <option value="White" <%= action == :edit && cat.color == "White" ? "selected" : "" %>>White</option>
    </select>
  </label>
  <br/>
  
  <label>
    Sex: 
    <input type="radio" name="cat[sex]" value="M" <%= action == :edit && cat.sex == 'M' ? "checked" : "" %>>Male</input>
    <input type="radio" name="cat[sex]" value="F" <%= action == :edit && cat.sex == 'F' ? "checked" : "" %>>Female</input>
  </label>
  <br/>
  <label>
    Description: 
    <textarea name="cat[description]"><%= cat.description %></textarea>
  </label>
  <br/>
  <input type="submit" value="<%= button_value %>">
</form>

cat99/app/views/cats/_cat_info.html.erb
<table>
  <tr>
    <th>Name</th>
    <th>Birth Date</th>
    <th>Age</th>
    <th>Color</th>
    <th>Description</th>
    <th>Sex</th>
  </tr>
  
  <tr>
    <th><%= cat.name %></th>
    <th><%= cat.birth_date %></th>
    <th><%= cat.age %></th>
    <th><%= cat.color %></th>
    <th><%= cat.description %></th>
    <th><%= cat.sex %></th>
  </tr>
</table>

cat99/app/views/cats/edit.html.erb
Edit cat!
<%= render "cat_form", { cat: @cat, action: :edit } %>

cat99/app/views/cats/index.html.erb
<a href="<%= new_cat_url %>">Make a new cat!</a>

<% @cats.each do |cat| %>
  <%= render 'cat_info', action: :index, cat: cat %>  
  <a href="<%= cat_url(cat) %>">View details</a>
<% end %>

cat99/app/views/cats/new.html.erb
Create New Cat

<%= render 'cat_form', action: :new, cat: @cat %>

cat99/app/views/cats/show.html.erb
<%= render 'cat_info', action: :show, cat: @cat %>  
<a href="<%= edit_cat_url %>">Edit Cat!</a>
<br/>
<a href="<%= cats_url %>">Return to main page</a>
<br/>

cat99/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cat99</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>